### ISSUE TITLE
Very slow...why?

### ISSUE THREAD

**Issue by dtamade** [sqlobject/sqlobject#133]
trans = con.transaction()
    for item in db_orig_hanzi.select():
        db_hanzi(hanzi=item.hanzi)
    trans.commit()

why?Do I use the wrong?

**Comment by phdru** [comment]
There are two problems with your code.

1, Transactions are not automatically used, you have to pass them to every SQL query command:

```python
   trans = con.transaction()
    for item in db_orig_hanzi.select(connection=trans):
        db_hanzi(hanzi=item.hanzi, connection=trans)
    trans.commit()
```

This is because there could be many connections and transactions opened at the same time. If you have just one connection and one transaction you can set the transaction as the transaction in sqlhub. Then it will be used automatically for every operations.

2. Mass insertion in SQLObject is slow. See [the FAQ](http://sqlobject.org/FAQ.html#how-to-do-mass-insertion) for an explanation and recommendation on using faster low-level APIs.

**Comment by dtamade** [comment]
thanks

**Comment by dtamade** [comment]
But it's still a little slow
Or SQL faster

**Comment by phdru** [comment]
Pure SQL will always be faster that any Python code that executes SQL. 😄

**Comment by dtamade** [comment]
My test results(Same data):

SqlObject=13s
SQLExpression=1.5s
PureSql=0.5s
😄

**Comment by phdru** [comment]
Perfectly normal results IMO.
